import { expect, test } from '@playwright/test'
import {
  createTestUserDataDir,
  launchApp,
  removePathWithRetry,
  seedWorkspaceState,
  testWorkspacePath,
} from './workspace-canvas.helpers'

const commandCenterModifier = process.platform === 'darwin' ? 'Meta' : 'Control'

test.describe('Space Archives', () => {
  test.skip('captures snapshots on archive and can be reviewed after restart', async () => {
    const userDataDir = await createTestUserDataDir()

    try {
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: false,
      })

      try {
        await seedWorkspaceState(window, {
          activeWorkspaceId: 'workspace-space-archives',
          workspaces: [
            {
              id: 'workspace-space-archives',
              name: 'workspace-space-archives',
              path: testWorkspacePath,
              nodes: [
                {
                  id: 'note-archive-1',
                  title: 'Archive Note',
                  position: { x: 220, y: 180 },
                  width: 320,
                  height: 220,
                  kind: 'note',
                  task: { text: 'Note full text\nLine 2' },
                },
                {
                  id: 'task-archive-1',
                  title: 'Archive Task',
                  position: { x: 580, y: 180 },
                  width: 420,
                  height: 260,
                  kind: 'task',
                  task: {
                    requirement: 'Task requirement full text\nLine 2',
                    status: 'doing',
                    linkedAgentNodeId: 'agent-archive-1',
                    lastRunAt: null,
                    autoGeneratedTitle: false,
                  },
                },
                {
                  id: 'agent-archive-1',
                  title: 'codex · default model',
                  position: { x: 420, y: 460 },
                  width: 420,
                  height: 320,
                  kind: 'agent',
                  status: 'standby',
                  agent: {
                    provider: 'codex',
                    prompt: 'Archive agent prompt',
                    model: null,
                    effectiveModel: null,
                    launchMode: 'new',
                    resumeSessionId: 'archive-session-123',
                    resumeSessionIdVerified: true,
                    executionDirectory: testWorkspacePath,
                    expectedDirectory: testWorkspacePath,
                    directoryMode: 'workspace',
                    customDirectory: null,
                    shouldCreateDirectory: false,
                  },
                },
              ],
              spaces: [
                {
                  id: 'space-archive-records',
                  name: 'Snapshot Space',
                  directoryPath: testWorkspacePath,
                  nodeIds: ['note-archive-1', 'task-archive-1', 'agent-archive-1'],
                  rect: { x: 180, y: 140, width: 720, height: 440 },
                },
              ],
              activeSpaceId: 'space-archive-records',
            },
          ],
        })

        await expect(window.locator('.note-node').first()).toBeVisible()

        await window.locator('[data-testid="workspace-space-switch-space-archive-records"]').click()
        await window.locator('[data-testid="workspace-space-menu-space-archive-records"]').click()
        await expect(window.locator('[data-testid="workspace-space-action-menu"]')).toBeVisible()
        await window.locator('[data-testid="workspace-space-action-archive"]').click()

        await expect(window.locator('[data-testid="space-worktree-window"]')).toBeVisible()
        await expect(window.locator('[data-testid="space-worktree-archive-submit"]')).toBeEnabled()
        await window.locator('[data-testid="space-worktree-archive-submit"]').click()
        await expect(window.locator('[data-testid="space-worktree-window"]')).toHaveCount(0)

        await expect
          .poll(async () => {
            return await window.evaluate(async () => {
              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  id?: string
                  spaceArchiveRecords?: Array<{
                    nodes?: Array<{ kind?: string; text?: string; requirement?: string }>
                  }>
                }>
              }

              const workspace =
                parsed.workspaces?.find(item => item.id === 'workspace-space-archives') ?? null
              const records = workspace?.spaceArchiveRecords ?? []
              const first = records[0]
              const nodes = first?.nodes ?? []
              const hasNote = nodes.some(
                node => node.kind === 'note' && node.text?.includes('Note full text') === true,
              )
              const hasTask = nodes.some(
                node =>
                  node.kind === 'task' &&
                  node.requirement?.includes('Task requirement full text') === true,
              )
              return { recordCount: records.length, hasNote, hasTask }
            })
          })
          .toEqual({ recordCount: 1, hasNote: true, hasTask: true })

        await window.keyboard.press(`${commandCenterModifier}+P`)
        const archivesCommand = window.locator(
          '[data-testid="command-center-item-command:space-archives"]',
        )
        await expect(archivesCommand).toBeVisible()
        await archivesCommand.click()

        const archivesWindow = window.locator('[data-testid="space-archives-window"]')
        await expect(archivesWindow).toBeVisible()

        const record = window.locator('[data-testid="space-archives-window-record"]').first()
        await expect(record).toBeVisible()
        await record.click()

        await expect(
          archivesWindow.locator('[data-testid="space-archives-window-replay-canvas"]'),
        ).toBeVisible()
        await expect(
          archivesWindow.locator('[data-testid="space-archives-window-replay-node"]'),
        ).toHaveCount(3)

        await expect(archivesWindow).toContainText('Note full text')
        await expect(archivesWindow).toContainText('Task requirement full text')
        await expect(archivesWindow).toContainText('Agent Sessions')
      } finally {
        await electronApp.close()
      }

      const relaunch = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: false,
      })

      try {
        const commandCenterButton = relaunch.window.locator(
          '[data-testid="app-header-command-center"]',
        )
        await expect(commandCenterButton).toBeVisible()
        await expect(commandCenterButton).toContainText('workspace-space-archives')

        await relaunch.window.keyboard.press(`${commandCenterModifier}+P`)
        const archivesCommand = relaunch.window.locator(
          '[data-testid="command-center-item-command:space-archives"]',
        )
        await expect(archivesCommand).toBeVisible()
        await archivesCommand.click()

        const archivesWindow = relaunch.window.locator('[data-testid="space-archives-window"]')
        await expect(archivesWindow).toBeVisible()

        const record = relaunch.window
          .locator('[data-testid="space-archives-window-record"]')
          .first()
        await expect(record).toBeVisible()
        await record.click()

        await expect(
          archivesWindow.locator('[data-testid="space-archives-window-replay-canvas"]'),
        ).toBeVisible()
        await expect(
          archivesWindow.locator('[data-testid="space-archives-window-replay-node"]'),
        ).toHaveCount(3)

        await expect(archivesWindow).toContainText('Note full text')
        await expect(archivesWindow).toContainText('Task requirement full text')
        await expect(archivesWindow).toContainText('Agent Sessions')

        await record.click({ button: 'right' })
        const contextMenu = relaunch.window.locator(
          '[data-testid="space-archives-window-record-context-menu"]',
        )
        await expect(contextMenu).toBeVisible()
        await relaunch.window.locator('[data-testid="space-archives-window-record-delete"]').click()

        await expect(
          relaunch.window.locator('[data-testid="space-archives-window-record"]'),
        ).toHaveCount(0)
        await expect
          .poll(async () => {
            return await relaunch.window.evaluate(async () => {
              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{ id?: string; spaceArchiveRecords?: Array<unknown> }>
              }

              const workspace =
                parsed.workspaces?.find(item => item.id === 'workspace-space-archives') ?? null
              return workspace?.spaceArchiveRecords?.length ?? 0
            })
          })
          .toBe(0)
      } finally {
        await relaunch.electronApp.close()
      }
    } finally {
      await removePathWithRetry(userDataDir)
    }
  })
})
