import { expect, test } from '@playwright/test'
import { execFile } from 'node:child_process'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import {
  clearAndSeedWorkspace,
  createTestUserDataDir,
  launchApp,
  removePathWithRetry,
  testWorkspacePath,
} from './workspace-canvas.helpers'

const execFileAsync = promisify(execFile)

async function createGitWorktree(payload: {
  branchName: string
  worktreePath: string
}): Promise<void> {
  await mkdir(path.dirname(payload.worktreePath), { recursive: true })
  await execFileAsync(
    'git',
    ['worktree', 'add', '-b', payload.branchName, payload.worktreePath, 'HEAD'],
    { cwd: testWorkspacePath },
  )
}

async function removeGitWorktree(payload: {
  branchName: string
  worktreePath: string
}): Promise<void> {
  try {
    await execFileAsync('git', ['worktree', 'remove', '--force', payload.worktreePath], {
      cwd: testWorkspacePath,
    })
  } catch {
    // ignore cleanup failures
  }

  try {
    await execFileAsync('git', ['branch', '-D', payload.branchName], { cwd: testWorkspacePath })
  } catch {
    // ignore cleanup failures
  }

  await removePathWithRetry(payload.worktreePath)
}

test.describe('Workspace Canvas - Agent Standby Banner Context', () => {
  test.skip('shows task/space/branch/pr chips and respects banner settings toggles', async () => {
    const userDataDir = await createTestUserDataDir()
    const stamp = Date.now()
    const branchName = `e2e/banner-context-${stamp}`
    const worktreeName = `wt-e2e-banner-context-${stamp}`
    const worktreePath = path.join(testWorkspacePath, '.opencove', 'worktrees', worktreeName)

    await createGitWorktree({ branchName, worktreePath })

    try {
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: true,
        env: {
          OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
          OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
          OPENCOVE_TEST_GITHUB_INTEGRATION: '1',
        },
      })

      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'task-banner-context',
              title: 'Trace flaky status updates',
              position: { x: 200, y: 160 },
              width: 460,
              height: 280,
              kind: 'task',
              status: null,
              task: {
                requirement: 'Verify standby banner context chips',
                status: 'todo',
                priority: 'medium',
                tags: ['e2e'],
                linkedAgentNodeId: null,
                lastRunAt: null,
                autoGeneratedTitle: false,
                createdAt: '2026-03-07T12:00:00.000Z',
                updatedAt: '2026-03-07T12:00:00.000Z',
              },
            },
          ],
          {
            spaces: [
              {
                id: 'space-banner-context',
                name: 'PR Space',
                directoryPath: worktreePath,
                nodeIds: ['task-banner-context'],
                rect: { x: 140, y: 120, width: 720, height: 520 },
              },
            ],
            activeSpaceId: 'space-banner-context',
            settings: {
              defaultProvider: 'codex',
              customModelEnabledByProvider: { codex: true },
              customModelByProvider: { codex: 'gpt-5.2-codex' },
              customModelOptionsByProvider: { codex: ['gpt-5.2-codex'] },
              githubPullRequestsEnabled: true,
            },
          },
        )

        const taskNode = window.locator('.task-node').first()
        await expect(taskNode).toBeVisible()

        await taskNode.locator('[data-testid="task-node-run-agent"]').click()

        const notificationList = window.locator(
          '[data-testid="app-notifications"] .app-notification',
        )
        const notification = notificationList.first()
        await expect(notification).toBeVisible({ timeout: 15_000 })

        await expect(
          notification.locator('[data-testid="app-notification-chip-task"]'),
        ).toContainText('Trace flaky status updates')
        await expect(
          notification.locator('[data-testid="app-notification-chip-space"]'),
        ).toContainText('PR Space')
        await expect(
          notification.locator('[data-testid="app-notification-chip-branch"]'),
        ).toContainText(branchName, { timeout: 15_000 })
        await expect(
          notification.locator('[data-testid="app-notification-chip-pr"]'),
        ).toContainText('#123', { timeout: 15_000 })

        await window.locator('[data-testid="app-header-settings"]').click()
        await expect(window.locator('.settings-panel')).toBeVisible()
        await window.locator('[data-testid="settings-section-nav-notifications"]').click()
        await expect(window.locator('#settings-section-notifications')).toBeVisible()

        const prToggle = window.locator(
          '[data-testid="settings-standby-banner-show-pr"] input[type="checkbox"]',
        )
        await expect(prToggle).toBeVisible()
        await prToggle.setChecked(false)

        await window.locator('.settings-panel__close').click()
        await expect(window.locator('.settings-panel')).toBeHidden()

        await expect(notification.locator('[data-testid="app-notification-chip-pr"]')).toHaveCount(
          0,
        )

        await window.locator('[data-testid="app-header-control-center"]').click()
        await expect(window.locator('[data-testid="control-center"]')).toBeVisible()
        await window.locator('[data-testid="control-center-toggle-agent-standby-banner"]').click()

        await expect(notificationList).toHaveCount(0)
      } finally {
        await electronApp.close()
      }
    } finally {
      await removeGitWorktree({ branchName, worktreePath })
      await removePathWithRetry(userDataDir)
    }
  })
})
