import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import {
  createTestUserDataDir,
  launchApp,
  seedWorkspaceState,
  testWorkspacePath,
} from './workspace-canvas.helpers'

async function seedCodexSessions(userDataDir: string): Promise<void> {
  const sessionDirectory = path.join(userDataDir, 'home', '.codex', 'sessions', '2026', '04', '29')
  await mkdir(sessionDirectory, { recursive: true })

  const currentRecord = JSON.stringify({
    type: 'session_meta',
    timestamp: '2026-04-29T00:10:00.000Z',
    payload: {
      id: 'resume-current',
      cwd: testWorkspacePath,
      timestamp: '2026-04-29T00:10:00.000Z',
    },
  })

  const targetRecord = JSON.stringify({
    type: 'session_meta',
    timestamp: '2026-04-29T00:30:00.000Z',
    payload: {
      id: 'resume-target',
      cwd: testWorkspacePath,
      timestamp: '2026-04-29T00:30:00.000Z',
    },
  })

  await writeFile(
    path.join(sessionDirectory, 'rollout-current.jsonl'),
    `${currentRecord}\n${JSON.stringify({
      type: 'message',
      id: null,
      role: 'user',
      content: [{ type: 'input_text', text: 'Keep the current task session active' }],
    })}\n`,
    'utf8',
  )
  await writeFile(
    path.join(sessionDirectory, 'rollout-target.jsonl'),
    `${targetRecord}\n${JSON.stringify({
      type: 'message',
      id: null,
      role: 'user',
      content: [{ type: 'input_text', text: 'Switch into the restored target task session' }],
    })}\n`,
    'utf8',
  )
}

test.describe('Workspace Canvas - Agent Session Switch', () => {
  test('switches the current agent node in place and archives the previous task binding', async () => {
    const userDataDir = await createTestUserDataDir()
    await seedCodexSessions(userDataDir)

    const { electronApp, window } = await launchApp({ userDataDir })

    try {
      await seedWorkspaceState(window, {
        activeWorkspaceId: 'workspace-agent-session-switch',
        workspaces: [
          {
            id: 'workspace-agent-session-switch',
            name: 'workspace-agent-session-switch',
            path: testWorkspacePath,
            nodes: [
              {
                id: 'task-session-switch',
                title: 'Task Session Switch',
                position: { x: 140, y: 180 },
                width: 420,
                height: 280,
                kind: 'task',
                task: {
                  requirement: 'Verify agent session switching',
                  status: 'doing',
                  priority: 'medium',
                  tags: [],
                  linkedAgentNodeId: 'agent-session-switch',
                  agentSessions: [],
                  lastRunAt: '2026-04-29T00:00:00.000Z',
                  autoGeneratedTitle: false,
                  createdAt: '2026-04-29T00:00:00.000Z',
                  updatedAt: '2026-04-29T00:00:00.000Z',
                },
              },
              {
                id: 'agent-session-switch',
                title: 'codex · gpt-5.2-codex',
                position: { x: 620, y: 180 },
                width: 520,
                height: 380,
                kind: 'agent',
                status: 'standby',
                startedAt: '2026-04-29T00:00:00.000Z',
                agent: {
                  provider: 'codex',
                  prompt: 'Switch to another saved session',
                  model: 'gpt-5.2-codex',
                  effectiveModel: 'gpt-5.2-codex',
                  launchMode: 'resume',
                  resumeSessionId: 'resume-current',
                  resumeSessionIdVerified: true,
                  executionDirectory: testWorkspacePath,
                  expectedDirectory: testWorkspacePath,
                  directoryMode: 'workspace',
                  customDirectory: null,
                  shouldCreateDirectory: false,
                  taskId: 'task-session-switch',
                },
              },
            ],
          },
        ],
      })

      const agentNode = window.locator('.terminal-node').first()
      await expect(agentNode).toBeVisible()
      await expect(window.locator('.terminal-node')).toHaveCount(1)

      await agentNode.locator('[data-testid="terminal-node-session-list"]').click()
      await expect(window.locator('[data-testid="terminal-node-session-menu"]')).toContainText(
        'Switch into the restored target task session',
      )
      await window.locator('[data-testid="terminal-node-session-menu-item-resume-target"]').click()

      const switchConfirm = window.locator('[data-testid="terminal-node-session-switch-confirm"]')
      await expect(switchConfirm).toBeVisible()
      await window
        .locator('[data-testid="terminal-node-session-switch-confirm-submit-resume-target"]')
        .click()

      await expect(window.locator('.terminal-node')).toHaveCount(1)
      await expect(agentNode).toBeVisible()

      await expect
        .poll(
          async () => {
            return await window.evaluate(async () => {
              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  id?: string
                  nodes?: Array<Record<string, unknown>>
                }>
              }

              const workspace = parsed.workspaces?.find(
                item => item.id === 'workspace-agent-session-switch',
              )
              const nodes = Array.isArray(workspace?.nodes) ? workspace.nodes : []
              const persistedAgentNode =
                nodes.find(item => item.id === 'agent-session-switch') ?? null
              const taskNode = nodes.find(item => item.id === 'task-session-switch') ?? null
              return {
                agentResumeSessionId:
                  persistedAgentNode &&
                  typeof persistedAgentNode.agent === 'object' &&
                  persistedAgentNode.agent
                    ? ((
                        persistedAgentNode.agent as {
                          resumeSessionId?: string | null
                        }
                      ).resumeSessionId ?? null)
                    : null,
                taskHistoryResumeSessionId:
                  taskNode &&
                  typeof taskNode.task === 'object' &&
                  taskNode.task &&
                  Array.isArray(
                    (
                      taskNode.task as {
                        agentSessions?: Array<{ resumeSessionId?: string | null }>
                      }
                    ).agentSessions,
                  )
                    ? ((
                        taskNode.task as {
                          agentSessions?: Array<{ resumeSessionId?: string | null }>
                        }
                      ).agentSessions?.[0]?.resumeSessionId ?? null)
                    : null,
              }
            })
          },
          { timeout: 30_000 },
        )
        .toEqual({
          agentResumeSessionId: 'resume-target',
          taskHistoryResumeSessionId: 'resume-current',
        })
    } finally {
      await electronApp.close()
    }
  })
})
