export const SPACE_EXPLORER_MP3_BASE64 = [
  'SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjcuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAA',
  'AAAAAABYaW5nAAAADwAAABUAAAtIAEdHR0dQUFBQUFpaWlpaY2NjY2NsbGxsdXV1dXV+fn5+foiIiIiI',
  'kZGRkZqampqao6Ojo6Otra2trba2tra/v7+/v8jIyMjI0dHR0dHb29vb5OTk5OTt7e3t7fb29vb2////',
  '/wAAAABMYXZjNjEuMTkAAAAAAAAAAAAAAAAkBh4AAAAAAAALSCpngI4AAAAAAP/7sMQAAAOoIV20MAAp',
  'CAyrvzLQAAAQAE9eAAAA7u7ucRwMDAwMDFnmQABwmOHj/8AAEeDYENnAHAIAOBQAAAAAAHSYlpWXJuJb',
  'IU9fw7mKIYUDYlAic6QHWE/oTUFd8J6O4Yb8LsSI9Rw/5kXi8ia/CQNFVUxBTUUzLjEwMFVVVVVVVVVV',
  'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQD4cH7QAAAAmZmAEi8dKh6sLwGxSDZWtFN4AABf',
  'ggCKykxBTUUzLjEwMKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqAAgA8AAAAAAVeBcJKinwKBFaTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgAI4PAAAAAACWWBcElQAH4NAAAp92Gg7tVMQU1FMy4xMDBV',
  'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQAH4NAAAAAAKuW4',
  'bj2ACccAAK4dhoNKykxBTUUzLjEwMKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqgAJ4PAAAAAAC2bw2ElQAI0Ar3YOBKeqTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqAAjQ8AAAAAALZsAsTCwrnQCBKMpM',
  'QU1FMy4xMDCqqqqq//sQxOaCwyQncdzAgCgdA264ApyFqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqAF44AAEs2AWPYBHOgEDu1UxBTUUzLjEwMFVVVVX/+xDE',
  '3wPBnBt1wB0kqBODboADpJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
  'VVVVVQAH4PAAAAAADZYDwLCwAJ4AhzoDAZGKTEFNRTMuMTAwqqqqqv/7EMTigMGwG3XAFORoKoOuOAWk',
  'lKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqAAng8AAAAAAI',
  's2A8TCwhzoDAhapMQU1FMy4xMDCqqqqq//sQxOIAwawdccAtJKAoA24QA6yHqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoACuDwAAAAAAi64KwiUACeAF+1wQEsqkxBTUUz',
  'LjEwMKqqqqr/+xDE4YHBsBt1wB0kaCUD7jgDrISqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqgAJ4PAAAAAAAbS4A4RKABfAALtsBAIWTEFNRTMuMTAwqqqqqv/7EMTgA8G4',
  'G3HAHWSoFwNuAAOslaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'AAng8AAAAAAG+TwHE0QAK4AW3OgICapMQU1FMy4xMDCqqqqq//sQxN4DwTQdcoAdJLAWA65AA6SWqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgAJ0PAAAAAAEbWAsKkACtDg',
  'AAG33YYBNUxBTUUzLjEwMFVVVVX/+xDE4YHBsBtzwAjkaCODbngDpJVVVVVVVVVVVVVVVVVVVVVVVVVV',
  'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUACtDgAAAAAAdduGZs0ACdAC6YYGrlTEFNRTMuMTAwVVVV',
  'Vf/7EMTgA8G4G3PAHSSoFgOuQAOglFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
  'VVVVVVVVVVVVVVVVVVUAC+DwAAAAAAdawJgVBzpAgAxMQU1FMy4xMDBVVVVV//sQxOGBwbAddcAdBCAj',
  'A654AySMVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQAK0OAAAAAA',
  'CbXFM2kAC+DwAACXSBgDFUxBTUUzLjEwMFVVVVX/+xDE4YHBvB1zwBUEICSDrngDoIRVVVVVVVVVVVVV',
  'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVAAvg8AAAAAAJtYHhqGdIGBYq',
  'TEFNRTMuMTAwqqqqqv/7EMThgcG4HXPAGSRgIwOueAOYlKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqAAvg8AAAAAANawPDUM6QUBwA+8Bc0AAAAP/xGBY+//sQxOIA',
  'waAdc8AcxKArg644BZiUK0QaoHSNvViTIDGAAAEDQCsCuE4IAAAAAABsRHMh8S/1LDAihqVf4unL4GlP',
  '+EnADbFH/JOrSdsNt/9C3FPquDa2f/5oceILHhFpcipMQU1FMy7/+xDE4QHBsB1xwB1kICADrjgCrIwx',
  'MDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqTEFNRTMuMTAwqqqqqv/7EMTfA8GgHXXAHGSgFAOugAOMlKqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqq//sQxOIAwaAdccAdZGApA664A4yUqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr/+xDE',
  '3wPBlB11wBxkoBIDroADjJSqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqv/7EMTeg8GQHXXAHGSgEgOugAOM',
  'lKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//sQxP+AAuQlddSQACkIjGw/MvIAqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqr/+xDE1gPAAAGkHAAAIAAANIAAAASqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq',
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg==',
].join('')

export const SPACE_EXPLORER_MP4_BASE64 = [
  'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAPWbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAA',
  'AAAD6AAAAggAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAwF0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAAB',
  'AAAAAAAAAggAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAA',
  'AGAAAAA2AAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAIIAAAEAAABAAAAAAJ5bWRpYQAAACBtZGhk',
  'AAAAAAAAAAAAAAAAAAAyAAAAGgBVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl',
  'b0hhbmRsZXIAAAACJG1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAA',
  'AQAAAAx1cmwgAAAAAQAAAeRzdGJsAAAAwHN0c2QAAAAAAAAAAQAAALBhdmMxAAAAAAAAAAEAAAAAAAAA',
  'AAAAAAAAAAAAAGAANgBIAAAASAAAAAAAAAABFUxhdmM2MS4xOS4xMDAgbGlieDI2NAAAAAAAAAAAAAAA',
  'GP//AAAANmF2Y0MBZAAK/+EAGWdkAAqs2UYn5sBEAAADAAQAAAMAyDxIllgBAAZo6+PLIsD9+PgAAAAA',
  'EHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAANfcAADX3AAAAGHN0dHMAAAAAAAAAAQAAAA0AAAIAAAAA',
  'FHN0c3MAAAAAAAAAAQAAAAEAAAB4Y3R0cwAAAAAAAAANAAAAAQAABAAAAAABAAAKAAAAAAEAAAQAAAAA',
  'AQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAE',
  'AAAAAAEAAAAAAAAAAQAAAgAAAAAcc3RzYwAAAAAAAAABAAAAAQAAAA0AAAABAAAASHN0c3oAAAAAAAAA',
  'AAAAAA0AAALbAAAADwAAAAwAAAAMAAAADAAAABQAAAAOAAAADAAAAAwAAAAUAAAADgAAAAwAAAAMAAAA',
  'FHN0Y28AAAAAAAAAAQAABAYAAABhdWR0YQAAAFltZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGlyYXBw',
  'bAAAAAAAAAAAAAAAACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYxLjcuMTAwAAAACGZy',
  'ZWUAAAOKbWRhdAAAAq4GBf//qtxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgcjMxMDggMzFl',
  'MTlmOSAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjMgLSBodHRwOi8v',
  'd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0xIHJlZj0zIGRlYmxvY2s9',
  'MTowOjAgYW5hbHlzZT0weDM6MHgxMTMgbWU9aGV4IHN1Ym1lPTcgcHN5PTEgcHN5X3JkPTEuMDA6MC4w',
  'MCBtaXhlZF9yZWY9MSBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0cmVsbGlzPTEgOHg4ZGN0PTEgY3Ft',
  'PTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9xcF9vZmZzZXQ9LTIgdGhyZWFkcz0y',
  'IGxvb2thaGVhZF90aHJlYWRzPTEgc2xpY2VkX3RocmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJs',
  'YWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJmcmFtZXM9MyBiX3B5cmFt',
  'aWQ9MiBiX2FkYXB0PTEgYl9iaWFzPTAgZGlyZWN0PTEgd2VpZ2h0Yj0xIG9wZW5fZ29wPTAgd2VpZ2h0',
  'cD0yIGtleWludD0yNTAga2V5aW50X21pbj0yNSBzY2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNf',
  'bG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBt',
  'YXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAACVliIQAO//+906/AptUwioD',
  'klcK9sqjoF1VD1q384qqVoWXSdLBAAAAC0GaJGxDf/6nhKmAAAAACEGeQniF/wRNAAAACAGeYXRCvwWM',
  'AAAACAGeY2pCvwWNAAAAEEGaaEmoQWiZTAhn//6eEfsAAAAKQZ6GRREsL/8ETQAAAAgBnqV0Qr8FjQAA',
  'AAgBnqdqQr8FjAAAABBBmqxJqEFsmUwIV//+OEYsAAAACkGeykUVLC//BE0AAAAIAZ7pdEK/BYwAAAAI',
  'AZ7rakK/BYw=',
].join('')

export const SPACE_EXPLORER_OGG_BASE64 = [
  'T2dnUwACAAAAAAAAAAB9qw1ZAAAAAISXXRQBHgF2b3JiaXMAAAAAAUSsAAAAAAAAgDgBAAAAAAC4AU9n',
  'Z1MAAAAAAAAAAAAAfasNWQEAAAAlvgeGDj////////////////+BA3ZvcmJpcwwAAABMYXZmNjEuNy4x',
  'MDABAAAAHwAAAGVuY29kZXI9TGF2YzYxLjE5LjEwMCBsaWJ2b3JiaXMBBXZvcmJpcyJCQ1YBAEAAACRz',
  'GCpGpXMWhBAaQlAZ4xxCzmvsGUJMEYIcMkxbyyVzkCGkoEKIWyiB0JBVAABAAACHQXgUhIpBCCGEJT1Y',
  'koMnPQghhIg5eBSEaUEIIYQQQgghhBBCCCGERTlokoMnQQgdhOMwOAyD5Tj4HIRFOVgQgydB6CCED0K4',
  'moOsOQghhCQ1SFCDBjnoHITCLCiKgsQwuBaEBDUojILkMMjUgwtCiJqDSTX4GoRnQXgWhGlBCCGEJEFI',
  'kIMGQcgYhEZBWJKDBjm4FITLQagahCo5CB+EIDRkFQCQAACgoiiKoigKEBqyCgDIAAAQQFEUx3EcyZEc',
  'ybEcCwgNWQUAAAEACAAAoEiKpEiO5EiSJFmSJVmSJVmS5omqLMuyLMuyLMsyEBqyCgBIAABQUQxFcRQH',
  'CA1ZBQBkAAAIoDiKpViKpWiK54iOCISGrAIAgAAABAAAEDRDUzxHlETPVFXXtm3btm3btm3btm3btm1b',
  'lmUZCA1ZBQBAAAAQ0mlmqQaIMAMZBkJDVgEACAAAgBGKMMSA0JBVAABAAACAGEoOogmtOd+c46BZDppK',
  'sTkdnEi1eZKbirk555xzzsnmnDHOOeecopxZDJoJrTnnnMSgWQqaCa0555wnsXnQmiqtOeeccc7pYJwR',
  'xjnnnCateZCajbU555wFrWmOmkuxOeecSLl5UptLtTnnnHPOOeecc84555zqxekcnBPOOeecqL25lpvQ',
  'xTnnnE/G6d6cEM4555xzzjnnnHPOOeecIDRkFQAABABAEIaNYdwpCNLnaCBGEWIaMulB9+gwCRqDnELq',
  '0ehopJQ6CCWVcVJKJwgNWQUAAAIAQAghhRRSSCGFFFJIIYUUYoghhhhyyimnoIJKKqmooowyyyyzzDLL',
  'LLPMOuyssw47DDHEEEMrrcRSU2011lhr7jnnmoO0VlprrbVSSimllFIKQkNWAQAgAAAEQgYZZJBRSCGF',
  'FGKIKaeccgoqqIDQkFUAACAAgAAAAABP8hzRER3RER3RER3RER3R8RzPESVREiVREi3TMjXTU0VVdWXX',
  'lnVZt31b2IVd933d933d+HVhWJZlWZZlWZZlWZZlWZZlWZYgNGQVAAACAAAghBBCSCGFFFJIKcYYc8w5',
  '6CSUEAgNWQUAAAIACAAAAHAUR3EcyZEcSbIkS9IkzdIsT/M0TxM9URRF0zRV0RVdUTdtUTZl0zVdUzZd',
  'VVZtV5ZtW7Z125dl2/d93/d93/d93/d93/d9XQdCQ1YBABIAADqSIymSIimS4ziOJElAaMgqAEAGAEAA',
  'AIriKI7jOJIkSZIlaZJneZaomZrpmZ4qqkBoyCoAABAAQAAAAAAAAIqmeIqpeIqoeI7oiJJomZaoqZor',
  'yqbsuq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq4LhIasAgAkAAB0JEdyJEdSJEVSJEdy',
  'gNCQVQCADACAAAAcwzEkRXIsy9I0T/M0TxM90RM901NFV3SB0JBVAAAgAIAAAAAAAAAMybAUy9EcTRIl',
  '1VItVVMt1VJF1VNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVN0zRNEwgNWQkAAAEA0Fpz',
  'zK2XjkHorJfIKKSg10455qTXzCiCnOcQMWOYx1IxQwzGlkGElAVCQ1YEAFEAAIAxyDHEHHLOSeokRc45',
  'Kh2lxjlHqaPUUUqxplo7SqW2VGvjnKPUUcoopVpLqx2lVGuqsQAAgAAHAIAAC6HQkBUBQBQAAIEMUgop',
  'hZRizinnkFLKOeYcYoo5p5xjzjkonZTKOSedkxIppZxjzinnnJTOSeack9JJKAAAIMABACDAQig0ZEUA',
  'ECcA4HAcTZM0TRQlTRNFTxRd1xNF1ZU0zTQ1UVRVTRRN1VRVWRZNVZYlTTNNTRRVUxNFVRVVU5ZNVbVl',
  'zzRt2VRV3RZV1bZlW/Z9V5Z13TNN2RZV1bZNVbV1V5Z1XbZt3Zc0zTQ1UVRVTRRV11RV2zZV1bY1UXRd',
  'UVVlWVRVWXZdWddVV9Z9TRRV1VNN2RVVVZZV2dVlVZZ1X3RV3VZd2ddVWdZ929aFX9Z9wqiqum7Krq6r',
  'sqz7si77uu3rlEnTTFMTRVXVRFFVTVe1bVN1bVsTRdcVVdWWRVN1ZVWWfV91ZdnXRNF1RVWVZVFVZVmV',
  'ZV13ZVe3RVXVbVV2fd90XV2XdV1YZlv3hdN1dV2VZd9XZVn3ZV3H1nXf90zTtk3X1XXTVXXf1nXlmW3b',
  '+EVV1XVVloVflWXf14XheW7dF55RVXXdlF1fV2VZF25fN9q+bjyvbWPbPrKvIwxHvrAsXds2ur5NmHXd',
  '6BtD4TeGNNO0bdNVdd10XV+Xdd1o67pQVFVdV2XZ91VX9n1b94Xh9n3fGFXX91VZFobVlp1h932l7guV',
  'VbaF39Z155htXVh+4+j8vjJ0dVto67qxzL6uPLtxdIY+AgAABhwAAAJMKAOFhqwIAOIEABiEnENMQYgU',
  'gxBCSCmEkFLEGITMOSkZc1JCKamFUlKLGIOQOSYlc05KKKGlUEpLoYTWQimxhVJabK3VmlqLNYTSWiil',
  'tVBKi6mlGltrNUaMQcick5I5J6WU0loopbXMOSqdg5Q6CCmllFosKcVYOSclg45KByGlkkpMJaUYQyqx',
  'lZRiLCnF2FpsucWYcyilxZJKbCWlWFtMObYYc44Yg5A5JyVzTkoopbVSUmuVc1I6CCllDkoqKcVYSkox',
  'c05KByGlDkJKJaUYU0qxhVJiKynVWEpqscWYc0sx1lBSiyWlGEtKMbYYc26x5dZBaC2kEmMoJcYWY66t',
  'tRpDKbGVlGIsKdUWY629xZhzKCXGkkqNJaVYW425xhhzTrHlmlqsucXYa2259Zpz0Km1WlNMubYYc465',
  'BVlz7r2D0FoopcVQSoyttVpbjDmHUmIrKdVYSoq1xZhza7H2UEqMJaVYS0o1thhrjjX2mlqrtcWYa2qx',
  '5ppz7zHm2FNrNbcYa06x5Vpz7r3m1mMBAAADDgAAASaUgUJDVgIAUQAABCFKMQahQYgx56Q0CDHmnJSK',
  'MecgpFIx5hyEUjLnIJSSUuYchFJSCqWkklJroZRSUmqtAACAAgcAgAAbNCUWByg0ZCUAkAoAYHAcy/I8',
  'UTRV2XYsyfNE0TRV1bYdy/I8UTRNVbVty/NE0TRV1XV13fI8UTRVVXVdXfdEUTVV1XVlWfc9UTRVVXVd',
  'WfZ901RV1XVlWbaFXzRVV3VdWZZl31hd1XVlWbZ1WxhW1XVdWZZtWzeGW9d13feFYTk6t27ruu/7wvE7',
  'xwAA8AQHAKACG1ZHOCkaCyw0ZCUAkAEAQBiDkEFIIYMQUkghpRBSSgkAABhwAAAIMKEMFBqyEgCIAgAA',
  'CJFSSimNlFJKKaWRUkoppZQSQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQggFAPhPOAD4P9ig',
  'KbE4QKEhKwGAcAAAwBilmHIMOgkpNYw5BqGUlFJqrWGMMQilpNRaS5VzEEpJqbXYYqycg1BSSq3FGmMH',
  'IaXWWqyx1po7CCmlFmusOdgcSmktxlhzzr33kFJrMdZac++9l9ZirDXn3IMQwrQUY6659uB77ym2WmvN',
  'PfgghFCx1Vpz8EEIIYSLMffcg/A9CCFcjDnnHoTwwQdhAAB3gwMARIKNM6wknRWOBhcashIACAkAIBBi',
  'ijHnnIMQQgiRUow55xyEEEIoJVKKMeecgw5CCCVkjDnnHIQQQiillIwx55yDEEIJpZSSOecchBBCKKWU',
  'UjLnoIMQQgmllFJK5xyEEEIIpZRSSumggxBCCaWUUkopIYQQQgmllFJKKSWEEEIJpZRSSimlhBBKKKWU',
  'UkoppZQQQimllFJKKaWUEkIopZRSSimllJJCKaWUUkoppZRSUiillFJKKaWUUkoJpZRSSimllJRSSQUA',
  'ABw4AAAEGEEnGVUWYaMJFx6AQkNWAgBAAAAUxFZTiZ1BzDFnqSEIMaipQkophjFDyiCmKVMKIYUhc4oh',
  'AqHFVkvFAAAAEAQACAgJADBAUDADAAwOED4HQSdAcLQBAAhCZIZINCwEhweVABExFQAkJijkAkCFxUXa',
  'xQV0GeCCLu46EEIQghDE4gAKSMDBCTc88YYn3OAEnaJSBwEAAAAAcAAADwAAxwUQEdEcRobGBkeHxwdI',
  'SAAAAAAAyADABwDAIQJERDSHkaGxwdHh8QESEgAAAAAAAAAAAAQEBAAAAAAAAgAAAAQET2dnUwAE6EQA',
  'AAAAAAB9qw1ZAgAAALLeBTwTHzwnJSUlJSUlJScnJSclJSUvgVzdqzqrurD/WgIEEADAjNottjfffPPN',
  'MAzDMAzDegCa2D0Hb9KeW1wFZiJAKgAAAAAAAAAAAAAA+v1gn84B0bUXXPCfow57/NIMF+zRrVu3P3zL',
  'm2+ePG5UAADe2L1YVynziDAxdvytYDoAAAAAYAAAAAAAAAC+zgYAAIOH53kBABPe2L2oVyn9FmXAzv0N',
  'TAcAAAAAAAAAAAAAADBnEQCABDNdSV0A3ti9qFcp/RZlwM79CqYDAAAAAAAAAAAAAAD48Q0AAEy+UB4D',
  'AN7YvVhXKfNhbcLJrQqmAwAAAAAAAAAAAAAAyOonAADIC4/XAQDe2L1YVynzsDIxTvyZYDoAAAAAAAAA',
  'AAAAAICv2wAAYFDw3g0A3ti9WDcp8xZpwsz9CaYDAAAAAAAAAAAAAADYHgUAAET/3kk/AN7YvVhXKfMW',
  'acKJPxuYDgAAAAAAAAAAAAAA4HojAADIanVmAADe2L1YVynzZmHCib8TTAcAAAAAAAAAAAAAAHC9CQAA',
  'ZIvrSQ8A3ti9WFcp87AyMU78mWA6AAAAgAAAAAAAAAAAbI8TAADi9aweADQA3tjdqjcp/RZpwIw/E0wH',
  'AAAAAAwAAAAAAADA11sBAMDgQPOGAGAC3ti9WFcp8xZlwo4/FUwHAAAAAAAAAAAAAAAQ1QsAQIIwKHQB',
  'AN7YvahXKf2IMjB2/JlgOgAAAIAAAAAAAAAAALx/BgAAk6eV6QfABN7YvVg3KfNmacKJPxNMBwAAAAAA',
  'AAAAAAAAMGeeAADg9BnrAQDe2L1YNynzFmnCjD8bmA4AAAAAAAAAAAAAAOC5MwAAqIzR5x0A3ti9WDcp',
  '8xZhwow/E0wHAAAAAAAAAAAAAADw3AkAAFQ8DfcBAN7YvWSv0vcjPm/MnQCQEgAAAAAAAAAAAAAAgOkp',
  'gNZdDeNYdj6dXo8ZYnnKi0oAflc9Nno//128bpjA1iN3ZtyeNIcRTRQDABgAAID/zayH2cv2NKdznHr9',
  '8XS+eXK+3elw7HOryNYzI/Z1YvV73/LjLD8Jyy8Jyy8JS+cWXzh6tl/Y+tl+Yetnf2jr2YtsXV1Ifq8l',
  'v9eS32vJ707yI5YfZ3mLZXWWcEDMamuwBZwB',
].join('')

export const SPACE_EXPLORER_WEBM_BASE64 = [
  'GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAfwEU2bdLpNu4tTq4QV',
  'SalmU6yBoU27i1OrhBZUrmtTrIHWTbuMU6uEElTDZ1OsggEjTbuMU6uEHFO7a1Osggfa7AEAAAAAAABZ',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxMYXZmNjEuNy4xMDBXQYxM',
  'YXZmNjEuNy4xMDBEiYhAgEAAAAAAABZUrmvIrgEAAAAAAAA/14EBc8WIZic3yDhj5tqcgQAitZyDdW5k',
  'iIEAhoVWX1ZQOYOBASPjg4QCYloA4JCwgWC6gTaagQJVsIRVuYEBElTDZ0B/c3OfY8CAZ8iZRaOHRU5D',
  'T0RFUkSHjExhdmY2MS43LjEwMHNz2mPAi2PFiGYnN8g4Y+baZ8ilRaOHRU5DT0RFUkSHmExhdmM2MS4x',
  'OS4xMDAgbGlidnB4LXZwOWfIoUWjiERVUkFUSU9ORIeTMDA6MDA6MDAuNTIwMDAwMDAwAB9DtnVGLOeB',
  'AKNDw4EAAICCSYNCAAXwA1YMOCQcGHgAAdB8sXq7dXsh775/7fmexaP9R+Hxmh/S+OD1GAAAAH3kRGQ9',
  'X2HTVztgrbVRbSVKRHAyb06TM11csCjhDjUN3oXbt5NI9nJJVOOnHijA0L7KULB9YCLNV8MkxQMF02t/',
  'h5FtY7zu5LIVx85PcmbIUH6Z3hC0bfT6PYvwKpX/0JXdRsDvsIv/eq3wbGGJiDqELD1A1B5SVXmVbyGL',
  'sfg83FhQpZ0Tz4Uk/PC5SCNPWu1LbEDKg2BnmEscnvOfSA/t84Ps8///JXT/7xYq7kHIUGt1JV/fDTyq',
  'yv2em0WVhyMqvYluub8aSy5nxRMYBUZ37aCKRT4tVeOjcbkVdogz7Q7WCNTiydhujYBnT8D/2OltfHFh',
  '9TbM0SZZUGD0qP4nnSuKidSZSxb4Stmn/tPB9B9p7JXUOC0r5XdLz9M/5Henud7jMcEi0EjbInTnWuZZ',
  'kk1LbPesh4M6rUfHwwLlQSJfYoMQBSAHU6l9nX2/Y0OJ5jsEtqMm0tf6NyuJesI6qahHhZEhgeqtF+Qf',
  '0sUb9ksJL8TfhzxSO5wP3pNrZaIAOSsjkx8Vn2746bLW9BBqBp0bvWGUA0PTolV7flPoVR5IFxptwcnS',
  '7+zStT50J8Am8nP8/v+814EEUkcajYLj2Zzl//5U4N/yVffue2OeShqf4DujRi+52bmiKs4aSdUtQEB6',
  'v0LJuUfzH1jmUz22a4d+GpT83gf//sTxJpOBzNkJMjNuEjR2KfKiBlLigzSVx/2mP69O67erjB2m0q26',
  'tgpvKiHVnKqev3RDmsK2ki1iHZKrvqKevLJ8bMmUDSOwT//pspHKmr13xw94D5BKeAToDMhIoDK0+tN7',
  'lOVptm8CRjIre+G0bJgb5wfbbFF1oKDVrWonSglLADrAlSJ6lClWlLlrb1+xLq9VDs9ogTWvGK6lEtK0',
  'Ds+2CWf7tyIo11My5wAqsFIXh9ZhWAjKBc0fDsnGKR7iuAsN10VoKXJ61Pm+AsqYwsqZNgz8sek6SfNB',
  'g+q+YsqPCI69b4ukhyIl4/0GteJAMoUqY7NySy4H9XiJswVzgemA2NKCZ/DJ17ACg5zoZkwPk88nDeal',
  '8TBqZXayuwy02jdZxN1g6vdEU4YrdiX+8jLElBvTI0TKxHXHZ9yfWlWmslycKcbfLWVSCE+6DFhhVo+n',
  '3bhrtwCR8KDDnKj90RMwf74W+Ukb/w3tdMJQ1fN73FAIzBo/NuhESj37SaD8KXJgzVM5qUdSUTxCtCN9',
  '101IdYpGAKOagQAoAIYAQJKcKFMAAAMgAAB6K3PwFLtTa3yjrYEAUACGAECSnBBR4AADcAAAekutBfjm',
  'Gv/7iU+BvPEqezTwMAemJ4D7sEXAAKOngQB4AIYAQJKMMFMAAANwAAB6TEDCllgKXrYrpFtsgWb2ehdi',
  '4tAgo8KBAKAAhgBAkow8UIAAA3AAAHpLu37vTiy3tkXrWcsEtPoSauIdrs49hpLmuHRXi9TPo2utvG8T',
  'wgU9kG/12ltH2gCjlIEAyACGAECSjCRTAAADIAAAWPYAo7mBAPAAhgBAkow0UeAAAyAAAHpLrVLtkDWL',
  'VoIpLjYOt9xHdns688IfLsiH5p3H1lOtjJ3yk8HoYACjnIEBGACGAECSjDxTAAADIAAAejXtHfEOxEYv',
  'oACj6oEBQACGAECSjChN4AADIAAAez48yhJSl4aPNce8z5s/KqOYw8yL0QdwQbYRHdVODXw/e3A/B5hh',
  'x+vWpHhQEA9GPkJVAlMbpFqLc/9X4/hvdA0tbBj1TIe4xKCfEsYXCLlP30DeBTMPK0CjmYEBaACGAECS',
  'jChTAAADIAAAekutFJOl8gCj2IEBkACGAMCS8JE3gAAMcAAAeyh7Bb+J6TJjT2AyI3wG9fhE5vdRLMNW',
  'xiPjsK+ssLJJBkTZ6CETe9wkEeAiFPoGxSKV4H9aQUu+dkC2tE1qax3ZmREA/mCjlIEBuACGAECSnBxT',
  'AAADIAAAWPYAo8OBAeAAhgBAkpwoUIAAAyAAAHpLrTn1LDdnh5VUlCuWOhtWaRktD/ze7wx9bwqu6nq9',
  '6Wowj1wiBJ0L0ptCAHMpLZ4gHFO7a5G7j7OBALeK94EB8YIBqPCBAw==',
].join('')

export function createSineWaveWavBuffer(options?: {
  durationMs?: number
  sampleRateHz?: number
  frequencyHz?: number
}): Buffer {
  const durationMs = options?.durationMs ?? 400
  const sampleRateHz = options?.sampleRateHz ?? 24_000
  const frequencyHz = options?.frequencyHz ?? 440
  const channelCount = 1
  const bitsPerSample = 16
  const bytesPerSample = bitsPerSample / 8
  const blockAlign = channelCount * bytesPerSample
  const sampleCount = Math.max(1, Math.round((sampleRateHz * durationMs) / 1_000))
  const dataSize = sampleCount * blockAlign
  const buffer = Buffer.alloc(44 + dataSize)

  buffer.write('RIFF', 0)
  buffer.writeUInt32LE(36 + dataSize, 4)
  buffer.write('WAVE', 8)
  buffer.write('fmt ', 12)
  buffer.writeUInt32LE(16, 16)
  buffer.writeUInt16LE(1, 20)
  buffer.writeUInt16LE(channelCount, 22)
  buffer.writeUInt32LE(sampleRateHz, 24)
  buffer.writeUInt32LE(sampleRateHz * blockAlign, 28)
  buffer.writeUInt16LE(blockAlign, 32)
  buffer.writeUInt16LE(bitsPerSample, 34)
  buffer.write('data', 36)
  buffer.writeUInt32LE(dataSize, 40)

  const amplitude = 0x5fff
  for (let sampleIndex = 0; sampleIndex < sampleCount; sampleIndex += 1) {
    const time = sampleIndex / sampleRateHz
    const sampleValue = Math.round(Math.sin(2 * Math.PI * frequencyHz * time) * amplitude)
    buffer.writeInt16LE(sampleValue, 44 + sampleIndex * bytesPerSample)
  }

  return buffer
}
