import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Task Selection Interactions', () => {
  test('toggles task node selection with shift-click on non-input body in mouse mode', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'mouse-shift-click-task-node',
            title: 'task-shift-click-toggle',
            position: { x: 220, y: 180 },
            width: 460,
            height: 320,
            kind: 'task',
            task: {
              requirement: 'Verify task toggle body semantics',
              status: 'todo',
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
        ],
        {
          settings: {
            canvasInputMode: 'mouse',
          },
        },
      )

      const taskMeta = window.locator('.task-node__meta').first()
      await expect(taskMeta).toBeVisible()

      await taskMeta.click()
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(1)

      const taskMetaBox = await taskMeta.boundingBox()
      if (!taskMetaBox) {
        throw new Error('task meta bounding box unavailable')
      }

      await window.keyboard.down('Shift')
      await window.mouse.move(
        taskMetaBox.x + taskMetaBox.width / 2,
        taskMetaBox.y + taskMetaBox.height / 2,
      )
      await window.mouse.down()
      await window.mouse.up()
      await window.keyboard.up('Shift')

      await expect(window.locator('.react-flow__node.selected')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })

  test('does not leave a task invisibly selected after clicking its input', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'mouse-task-input-selection-node',
            title: 'task-input-selection',
            position: { x: 220, y: 180 },
            width: 460,
            height: 320,
            kind: 'task',
            task: {
              requirement: 'Clicking this input should not select the task',
              status: 'todo',
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
        ],
        {
          settings: {
            canvasInputMode: 'mouse',
          },
        },
      )

      const requirementInput = window
        .locator('[data-testid="task-node-inline-requirement-input"]')
        .first()
      await expect(requirementInput).toBeVisible()

      await requirementInput.click()
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(0)

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()
      await pane.click({ position: { x: 40, y: 40 } })
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })

  test.skip('keeps task requirement input focused after clearing selection', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'mouse-task-input-focus-node',
            title: 'task-input-focus',
            position: { x: 220, y: 180 },
            width: 460,
            height: 320,
            kind: 'task',
            task: {
              requirement: 'Clicking this input should keep focus after selection clears',
              status: 'todo',
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
        ],
        {
          settings: {
            canvasInputMode: 'mouse',
          },
        },
      )

      const taskHeader = window.locator('.task-node__header').first()
      await expect(taskHeader).toBeVisible()
      await taskHeader.click()
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(1)

      const requirementInput = window
        .locator('[data-testid="task-node-inline-requirement-input"]')
        .first()
      await expect(requirementInput).toBeVisible()
      await requirementInput.click()
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(0)
      await expect(requirementInput).toBeFocused()
    } finally {
      await electronApp.close()
    }
  })

  test('keeps task window focus ring stable while typing', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'mouse-task-input-focus-ring-node',
            title: 'task-input-focus-ring',
            position: { x: 220, y: 180 },
            width: 460,
            height: 320,
            kind: 'task',
            task: {
              requirement: 'Typing should not make the task window border wink',
              status: 'todo',
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
        ],
        {
          settings: {
            canvasInputMode: 'mouse',
          },
        },
      )

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      const readBorderColor = async (): Promise<string> => {
        return await taskNode.evaluate(element => {
          const style = window.getComputedStyle(element)
          return style.borderColor
        })
      }

      const selectionBorderColor = await taskNode.evaluate(element => {
        const style = window.getComputedStyle(element)
        return style.getPropertyValue('--cove-node-selection-border').trim()
      })

      const defaultBorderColor = await taskNode.evaluate(element => {
        const style = window.getComputedStyle(element)
        return style.getPropertyValue('--cove-node-border').trim()
      })

      const normalizeColor = (value: string) => value.replaceAll(/\s+/g, '').toLowerCase()

      const taskHeader = window.locator('.task-node__header').first()
      await expect(taskHeader).toBeVisible()
      await taskHeader.click()
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(1)

      await expect
        .poll(async () => normalizeColor(await readBorderColor()), {
          message: 'expected selected task border color to match selection color',
        })
        .toBe(normalizeColor(selectionBorderColor))

      const requirementInput = window
        .locator('[data-testid="task-node-inline-requirement-input"]')
        .first()
      await expect(requirementInput).toBeVisible()
      await requirementInput.click()
      await expect(window.locator('.react-flow__node.selected')).toHaveCount(0)
      await expect(requirementInput).toBeFocused()

      await requirementInput.type(' - test typing')

      const borderAfterFocus = normalizeColor(await readBorderColor())
      expect(borderAfterFocus).toBe(normalizeColor(selectionBorderColor))
      expect(borderAfterFocus).not.toBe(normalizeColor(defaultBorderColor))
    } finally {
      await electronApp.close()
    }
  })
})
